on: [push]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.AZURE_USERNAME }}
        # Container registry password
        password: ${{ secrets.AZURE_PASSWORD }} 
        # Container registry server url
        login-server: ngoble.azurecr.io/personal/website
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@ab83648e2e224cfeeab899e23b639660765c3a89
      uses: docker/build-push-action@v1.1.1
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ngoble.azurecr.io/personal/website
        # Docker repository to tag the image with
        repository: personal-website
        # Always attempt to pull a newer version of the image
        always_pull: true
