on: [push]

jobs:
  build-and-deploy:
    name: Build and Deploy
    container:
      image: node
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build :latest
        uses: actions-hub/docker/login@master
        with: 
          args: build -t personal-website .
          
      - name: Tag :latest
        uses: actions-hub/docker/login@master
        with: 
          args: tag personal-website:latest nickerzb/personal-website

      - name: Push to docker hub :latest
        uses: actions-hub/docker@master
        with:
          args: push nickerzb/personal-website
